version: '3'

services:

  postgres:
    container_name: burse_pg
    image: postgres
    volumes:
      - pg-burse-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=local-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432

volumes:
  pg-burse-data:
